baseURL: 'https://diiorio.me/'
languageCode: en-us
title: Anthony Di Iorio
pagination:
  pagerSize: 10
theme: PaperMod

# Update sitemap with git dates
enableGitInfo: true

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

enableEmoji: true

#services:
#  googleAnalytics:
#    ID: 

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "Anthony Di Iorio"
  description: "A Technology Blog by Anthony Di Iorio. Montreal, QC."
  keywords: [Blog, Anthony Di Iorio, Montreal, Tech, Home Lab, VE2HEW]
  author: Anthony Di Iorio
  images: ["/summary.jpg"]
  DateFormat: "January 2, 2006"
  defaultTheme: dark # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: false
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  social:
    fediverse_creator: "@VE2HEW@mastodon.social"

  assets:
    disableHLJS: true # to disable highlight.js
    # disableFingerprinting: true
    favicon: "/favicon.ico"
    favicon16x16: "/favicon-16x16.png"
    favicon32x32: "/favicon-32x32.png"
    apple_touch_icon: "/apple-touch-icon.png"
    safari_pinned_tab: "/apple-touch-icon.png"

  label:
    text: "Anthony Di Iorio"
    icon: /apple-touch-icon.png
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: false # needs to be explicitly set
    title: Anthony Di Iorio
    subtitle: "Good milk = strong bones."
    imageUrl: "/anthony.jpg"
    imageWidth: 120
    imageHeight: 120
    imageTitle: Me
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags

  # home-info mode
  homeInfoParams:
    Title: "Hi."
    Content: >
      Welcome to my blog.

      - I'm Anthony from [**Montreal**](https://en.wikipedia.org/wiki/Montreal). I like to write about tech stuff.

      - Sometimes on the airwaves as 📻 [**VE2HEW**](https://ve2hew.com) 

  socialIcons:
    - name: mastodon
      url: 'https://mastodon.social/@VE2HEW'
    - name: bluesky
      url: 'https://bsky.app/profile/diiorio.me'
    - name: instagram
      url: https://instagram.com/ant.diiorio
    - name: youtube
      url: 'https://youtube.com/anthonydiiorio'
    - name: flickr
      url: 'https://flickr.com/photos/anthonydiiorio/'
    - name: rss
      url: /index.xml

  #analytics:
  #  google:
  #    SiteVerificationTag: "XYZabc"
  #  bing:
  #    SiteVerificationTag: "XYZabc"
  #  yandex:
  #    SiteVerificationTag: "XYZabc"

  cover:
    hidden: false # hide everywhere but not in structured data
    hiddenInList: false  # hide on list pages and home
    hiddenInSingle: false # hide on single page

  #editPost:
  #  URL: "https://github.com/<path_to_repo>/content"
  #  Text: "Suggest Changes" # edit text
  #  appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.2
    minMatchCharLength: 2
    keys: ["title", "permalink", "summary", "content"]

markup:
  highlight:
    anchorLineNos: false
    codeFences: true
    guessSyntax: false
    hl_Lines: ""
    hl_inline: false
    lineAnchors: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    noHl: false
    style: monokai
    tabWidth: 4

outputs:
    home:
        - HTML
        - RSS
        - JSON # necessary for search

menu:
  main:
    - identifier: Search
      name: Search
      url: /search
      weight: 10
    - identifier: Contact
      name: Contact
      url: /contact
      weight: 20